### ISSUE TITLE
How can we fetch all the columns from the ledger table 

### ISSUE THREAD

**Issue by worldfellow** [dhananjay1405/tally-database-loader#11]
As the database structure is limited and we want all the column data from tally ledger table  can we add all the columns from the ledger table ?

**Comment by dhananjay1405** [comment]
You can add as many column of Tally you want to this utility. Utility offers easy field / database expansion. This is already covered in documentation. You need to define custom fields in tally-export-config.yaml & parallelly in database structure. You can refer Tally Developer for the detailed Tally Schema. Have a look at existing fields in tally export config, you will know the complete game. You can even add User Defined Fields created by TDL Developers also.

Reason of adding limited fields is to keep database structure manageable, as not every organisation uses all the fields of Tally. Those who require can always expand database as per requirement
