### ISSUE TITLE
Support for Oracle Autonomuse Database

### ISSUE THREAD

**Issue by haansanghavi** [dhananjay1405/tally-database-loader#12]
First and Foremost, This utitlity is awesome. 

Is there any plan to support oracle autonomus database which gives 20GB of free database space for always free. 

I was planning to create APEX No Code application which serves me for number of analysis and dashboards. 

It would be really helpful to just see all client's previous sales on dashboard by just one click.

**Comment by dhananjay1405** [comment]
I didn't tried Oracle Cloud hosted autonomous database (as generally I have worked only with that typical one 19C we install on Windows Server). This project heavily depends on 3rd party tried, tested & stable Node.JS package (or library), for data connections & data transfer. For oracle just handful NPM packages are available. I am even trying for IBM DB2, but again it has some story like Oracle.

For future if demand for integration with few more such technologies comes, I may even plan to migrate this project from Node.JS to C++, as I have found majority database technologies offering C++ drivers. Also, it will be possible to compile project for all 3 platforms (Windows / Linux / Apple), which is my another objective. At that time, not just Oracle, but many technologies will come in ambit.
