### ISSUE TITLE
Error while incremental sync

### ISSUE THREAD

**Issue by NXC-Controls** [dhananjay1405/tally-database-loader#18]
1. Full sync completed successfully
2. switched to incremental sync with below settings
3. `"tally": {
        "server": "192.168.0.181",
        "port": 9000,
        "sync": "incremental",
        "company": ""
    }` 
4. Getting error

Error from tally.processMasters() at 2023-01-19 13:21:24
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'from mst_group as t join mst_group as s on s.guid = t._parent' at line 1

to use near 'from mst_group as t join mst_group as s on s.guid = t._parent' at line 1
ER_PARSE_ERROR
om mst_group as t join mst_group as s on s.guid = t._parent' at line 1
42000

**Comment by dhananjay1405** [comment]
MariaDB & MySQL I don't think incremental sync will work, since in this type of sync, I have used few SQL syntax, which are not compatible with both. PostgreSQL & Microsoft SQL Server are the database platforms I am looking to support on in coming future.
