### ISSUE TITLE
Cost centre details for sales entries with inventory vouchers are not captured in trn_cost_centre table 

### ISSUE THREAD

**Issue by devacodingid** [dhananjay1405/tally-database-loader#19]
Problem Statement:

The utility captures the CostCentreAllocations from AllLedgerEntries. In general entries it works like a charm.
However, in case of Sales transaction with Inventory item (even though we use the tally with accounts only feature) the cost centre details are available only under AllInventoryEntries.

It can be found under ALLINVENTORYENTRIES/ACCOUNTINGALLOCATIONS/CATEGORYALLOCATIONS/COSTCENTREALLOCATIONS
whereas in normal entries it will be captured under
LEDGERENTRIES/CATEGORYALLOCATIONS/COSTCENTREALLOCATIONS

Suggestion: 
As a temp fix, Can we capture the cost centre details on trn_batch table also. so that where the data is missing in trn_cost_centre we can join from trn_batch table.

**Comment by dhananjay1405** [comment]
@devacodingid yes, you can handle this specific scenario on case to case basis, by tweaking file **tally-export-config.yaml**
Currently for **trn_cost_centre** table, I have queried object tree **Voucher.AllLedgerEntries.CostCentreAllocations** but you can modify this to **Voucher.AllInventoryEntries.AccountingAllocations.CategoryAllocations.CostCentreAllocations** to yield this output.
