### ISSUE TITLE
Suggestion: Move to Knex

### ISSUE THREAD

**Issue by adarshmadrecha** [dhananjay1405/tally-database-loader#2]
Currently the code calls the mysql and mssql libraries directly.
Instead of writing helper functions for each database, move to [Knex](http://knexjs.org/), which has support for larger number SQL databases.

Benefits
1. Consistent query construction
2. In long term, easy maintenance of code base
2. No need to test and take care of database specific syntax.

### Current
```
import * as mysql from 'mysql';
import * as mssql from 'tedious';
```

### Proposed
```
import Knex from 'knex';
````

**Comment by dhananjay1405** [comment]
@adarshmadrecha a good suggestion. I checked its documentation on NPM and its official documentation website, and found it to be a pure SQL Query builder. So including Knex may lead to following

1. Being a pure query building, it ultimately needs installation of **mysql** and **mssql** package, for execution of queries
2. It has a long Dependency tree of other NPM modules, which will increase memory footprints of Node process.
3. Knex focuses more on cross-database query building without worrying of SQL syntax construction suitable when you intend to retrieve rows, joins, execute schema creation/modification queries too . This project has minimal complexity of SQL syntax like truncate, insert, which are same across all SQL platform.
4. Only difference in syntax occurs for file based bulk loading i.e. SQL Server (BULK INSERT) and MySQL (LOAD DATA INFILE), which Knex does not offer solution.
5. Streaming insert queries (in Knex) requires preparing array of object in Javascript, which will again increase code. Utility dumps data in CSV format (with columns double quoted). This text dump format is almost near to INSERT statement with multiple values. Even that's the reason, I did not used tedious (MS-SQL) package insert query streaming function.

So, these are the reasons for which I prefer to keep this solution close to near-native packages of respective Database Servers.

There will be hardly any code level changes if things work stably. Project will expand more on inclusion of fields and tables of Tally, with testing on multiple client Tally data.
