### ISSUE TITLE
How to get outstanding details of sundry debtors from tally in power bi connected thru odbc

### ISSUE THREAD

**Issue by Rachnajn** [dhananjay1405/tally-database-loader#20]

**Comment by dhananjay1405** [comment]
Not aware of the ODBC method, as I don't use ODBC.
If you are using this utility, then you can query trn_bill table, which contains details of New Ref and Against Ref. So, practically, you can query both information & then compare it to find which bills got paid & which are outstanding.

**Comment by Rachnajn** [comment]
Thanks
