### ISSUE TITLE
GSTN Details

### ISSUE THREAD

**Issue by vijender973** [dhananjay1405/tally-database-loader#21]
How can we Extract HSN Summary and GSTN wise sales report using this utility

**Comment by dhananjay1405** [comment]
I have captured master level data for GSTN & HSN in table **mst_gst_effective_rate** . But transaction level details I have not integrated those fields in utility, as I am waiting for some good sample data, which will serve as guidance for me to extract & integrate those fields in the utility. I will keep this thread open as database expansion request till relevant fields are integrated. Appreciate for bringing this to notice.

**Comment by fast-books** [comment]
I am unable to get this data even through XML. Is there a way to extract the HSN data in the xml through the invoice voucher export. Then may be we can figure out something?

**Comment by dhananjay1405** [comment]
HSN & GSTN details available in table **mst_stock_items** and **mst_ledger** respectively

**Comment by vijender973** [comment]
Thanks sir for update.......
