### ISSUE TITLE
How to get Tally Prime eInvoice data

### ISSUE THREAD

**Issue by b4allb4u** [dhananjay1405/tally-database-loader#24]
Hi Sir@dhananjay1405

Greetings of the day! 

First of all, Thanks a lot for your great utility.. it's an excellent utility for creating unbelievable reports on Google Sheets with the help of Query language.  

Please help how to get the Tally Prime einvoicing data by using your tally connection utility.

Thanks in Adv 

B4ALLB4U

**Comment by dhananjay1405** [comment]
@b4allb4u utility supports adding of fields from Tally as per your choice, which you require for capturing eInvoice data. First step is identification of field name in Tally. Just export voucher with eInvoice data into XML format. Open that XML file via Notepad++. Then try to search for that information, which you would find nested in XML tags, which is the field name used by the tally. Check the location of collection of that field in which it is nested. File named **tally-export-config.yaml** instructs utility to extract the fields from Tally. All the trn_xxx table correspond to some sub-collection of Voucher collection. Just add that field into respective trn_xxx and database-structure in same order (and then drop & re-create that specific table in database). You might require few trial-error.
