### ISSUE TITLE
Is it possible to get the time a voucher was created at?

### ISSUE THREAD

**Issue by clmnin** [dhananjay1405/tally-database-loader#25]
Current result only specify the date
```
trn_voucher -> date
```

**Comment by dhananjay1405** [comment]
@clmnin unfortunately Tally does not expose actual date/time of posting voucher in the system, via dedicated in-built field. I have seen many people creating User Defined Field (a.k.a. storage in TDL) to achieve this.

**Comment by clmnin** [comment]
Thank you. I'll look into how to create a UDF
