### ISSUE TITLE
unable to import the database getting this error Cannot detect First/Last voucher date from company

### ISSUE THREAD

**Issue by JEEVAN28** [dhananjay1405/tally-database-loader#28]
Hi,

I am facing same issue in case of Release 4.0 

https://github.com/dhananjay1405/tally-database-loader/issues/9

I checked with keeping company name as blank then it works but in case company name is specified then issue comes.

Regards
Jeevan Pendhari

**Comment by dhananjay1405** [comment]
@JEEVAN28 I have myself verified, writing company name works perfectly even in Tally Prime 4.0
Can you confirm below fix of escape (or substitute) special characters in Company name as below:
& = &amp;
' = &apos;
> = &gt;
< = &lt;

Your company name in config.json should look something like this:
Ram & Shyam Enterprises = Ram &amp; Shyam Enterprises

If this works, then I will apply handling for this in the utility itself in the next release.

**Comment by JEEVAN28** [comment]
Yes this worked there was & char in company name. Thanks @dhananjay1405
