### ISSUE TITLE
suggestion  trn_inventory quantity issue

### ISSUE THREAD

**Issue by NXC-Controls** [dhananjay1405/tally-database-loader#31]
i have a invoice with quantity actual + billed 
![image](https://github.com/dhananjay1405/tally-database-loader/assets/62667104/08f9c877-8f55-4b8f-9aa1-c8609ed93bc9)
but when we check in trn_inventory it only shows actual not billed 
![image](https://github.com/dhananjay1405/tally-database-loader/assets/62667104/7f3dd77c-da6d-4737-9627-bfc4187fa548)

it may be lead to miscalculation , so suggesting to use billed quantity instead of actual in trn_inventory 

it took me almost a week to match actual physical inventory with generated report .

**Comment by dhananjay1405** [comment]
@NXC-Controls in that scenario I will suggest you with 2 options

1. In **tally-export-config.yaml** file locate trn_inventory table quantity field. Modify **ActualQty** with **BilledQty**
2. Delete quantity field and instead introduce 2 fields ActualQty and BilledQty in tally-export-config.yaml, which will give you better reporting. Do not forgot to apply the same to **database-structure.sql** to keep it aligned with _tally-export-config.yaml_

Majority users are using quantity field without configuring actual vs bill. In that scenario, Tally assigns same value to both the fields. That was the reason I chose ActualQty.

Feel free to play with tally-export-config.yaml which provides complete control on fields of Tally and expansion of tables (Collections) and fields of Tally, which you might require. I have deliberately defined limited fields of Tally, as I intend to keep database structure simple and export faster.

**Comment by NXC-Controls** [comment]
@dhananjay1405 Thank you for quick response,
i need one more help, is there any way to get list of all available fields of tally database, so we can select which one to use in tally-export-config.yaml .

**Comment by dhananjay1405** [comment]
@NXC-Controls you will get list of all the available fields in Tally Developer software under the schema tab, where each collection and fields under it is listed. Just install educational version of Tally Developer and you are good to grab any field from the respective collection and add it to the utility. I remember in one of the video on my Excel Kida channel, I have even demonstrated this.
