### ISSUE TITLE
post-import-scripts/opening-transaction.sql --- Is not relevant anymore

### ISSUE THREAD

**Issue by pharmankur** [dhananjay1405/tally-database-loader#34]
With database field changes applied in V 1.0.31 ; the following query has become redundant. 
https://github.com/dhananjay1405/tally-database-loader/blob/main/post-import-scripts/opening-transaction.sql

> /*  Post Import Script : Opening Transactions
    SQL for treating opening balance as a transaction to speed-up calculation
*/
insert into trn_voucher(guid,date,voucher_type,is_invoice,is_accounting_voucher,is_order_voucher) values('00000000-0000-0000-0000-000000000000-00000001','1999-12-31','opening balance',0,1,0);
insert into trn_accounting(guid,ledger,amount)
select
	'00000000-0000-0000-0000-000000000000-00000001' 'guid',
    l.name,
    l.opening_balance
from mst_ledger l
where l.opening_balance <> 0
;

Present fields in trn_voucher are ---> [ Fields in **_BOLD_** are missing fields from query ]
guid,date,voucher_type,**_voucher_number_**,_reference_number_,**_reference_date_**,**_narration_**,**_party_name_**,**_place_of_supply_**,is_invoice,is_accounting_voucher,**_is_inventory_voucher_**,is_order_voucher

Present fields in trn_accounting are --->  [ Fields in **_BOLD_** are missing fields from query ] 
guid,ledger,amount,**_amount_forex_**,**_currency_**

Please update the script if to be used further and add some documentation about use of the query 
Also suggest, if this is really useful , make it as a standard while importing data. 
If the thing is not relevant anymore , discard it from code.

**Comment by dhananjay1405** [comment]
issue fixed in the commit 07b7038 by removing those files to avoid further ambiguity
