### ISSUE TITLE
Unable to get data regarding company invoices.

### ISSUE THREAD

**Issue by tejus-devstree** [dhananjay1405/tally-database-loader#35]
Hi @dhananjay1405 @pharmankur,

I am unable to get invoice details like items, quantity, rate  cost, etc.
Could u guide me on which csv file to look into.

I tried with Plain Tally ODBC Driver was able to get table row count, found that i have around 11 thousand records in a table called "CompanyVoucher", i am unable to even perfrom simple select query on that table, every time i try, it crashes the  Tally Prime, any guidance regarding it.

PS : i don't have much experience in Tally Ecosystem just nodejs.

Thank you for your time and assistance!

**Comment by dhananjay1405** [comment]
@tejus-devstree Tally ODBC Driver personally I do not use due to its limitations, so cannot help you with ODBC.
Look for the file **trn_inventory** which contains breakup of item, quantity, amount.

**Comment by tejus-devstree** [comment]
@dhananjay1405 thank you.

**Comment by tejus-devstree** [comment]
@dhananjay1405,

when i was going through issues i found one regarding support for mongodb, i am willing to contribute that feature.

**Comment by dhananjay1405** [comment]
@tejus-devstree utility supports export of JSON files by setting _technology_ to **json** which you can then load it into MongoDB via Mongo shell. I guess on searching I found mongoimport command which can load these json files into your MongoDB. Feel free to come up with the fork of this project, where you can build out all these things. I would love to see your fork once you get some success. Happy to help you with anything from my end, for your MongoDB fork of this project.
