### ISSUE TITLE
Names non appearing in the CSV extracts

### ISSUE THREAD

**Issue by sau6402** [dhananjay1405/tally-database-loader#4]
Hi @dhananjay1405 ,

The Utility creates CSVs pertaining to each table. 
When I tried to check for data, I could only see 1s and 0s in majority of the columns.

PFA CSV sample files generated by the utility.
[CSV Sample Files.zip](https://github.com/dhananjay1405/tally-database-loader/files/6226547/CSV.Sample.Files.zip)

Please guide me on what I can do to see the actual data.

--
Regards
Saurabha J

**Comment by dhananjay1405** [comment]
Duplicate of #3
