### ISSUE TITLE
unable to import the database getting this error Cannot detect First/Last voucher date from company

### ISSUE THREAD

**Issue by worldfellow** [dhananjay1405/tally-database-loader#9]
Error from tally.processMasters() 
Cannot detect First/Last voucher date from company

**Comment by dhananjay1405** [comment]
Please ensure you are using updated version of utility, as recently I improved on error handling with proper messages shown in error-log.txt
Also, if possible, kindly share your config.json (or it's screenshot), it may give some idea of error (ensure you remove your passwords & server IP address, if it points to cloud database, before sharing that file)

**Comment by bharatadnani** [comment]
I am also facing same issue, here is the configuration file. Mine is the latest version
![configuration error](https://user-images.githubusercontent.com/95958812/145700555-47fb3ffe-3049-4d1c-90d0-c4a866e66cd0.jpg)

**Comment by dhananjay1405** [comment]
@bharatadnani 
config.json seems perfect
try setting company name as blank & just keep single company activated in Tally
"company": ""
There is a possibility that company name could have minor mismatch (typically sometime spaces are there in company name), which creates this issue

**Comment by dhananjay1405** [comment]
@bharatadnani 
one more cause of issue.
Tally Prime version 2.0.1 specifically has bugs due to which retrieving data programmatically in CSV format has broken down. Utility depends on CSV format instead of XML. Tally Solutions has accepted this bug & and have promised to resolve this in next release.
So as of now only fix is to revert back to version 2.0.0 of Tally Prime

**Comment by adarshmadrecha** [comment]
@dhananjay1405 Yes, I am also facing issue in v2.0.1

**Comment by dhananjay1405** [comment]
@adarshmadrecha yes, it is a real headache which many users are facing. In this recent release 2.0.1 of Tally Prime, there is a bug, where even when I have specified Tally XML Server to return output in CSV format, it returns back in XML. So the whole utility crashes. CSV is very clean, faster & memory optimized when compared to XML.

Reverting back Tally Prime to 2.0.0 requires removal & clean install of Tally, and is really cumbersome. Let's hope Tally Solution takes cognizance of this seriously & correct their programming errors. There has been a long history of ignoring concerns & suggestions of open-source project developers, by corporates. So let's see if Tally Solutions is really keen to solve the bugs I have submitted to them. Future of this project depends on them. I have literally paused development of new features like Graphical Interface, Excel export option etc, which I had planned as next improvement.

I will keep this thread open, until we get some positive news and action from Tally Solutions. I will request everyone in this thread (@worldfellow  @bharatadnani and @adarshmadrecha ) to keep an eye on version 2.0.2 & request to update me on this thread, when next version is released.

**Comment by rvaishnow** [comment]
hi, 
Thanks for the Great Utility Tool, i was able to use it following the documentation and troubleshooting (For Tally 2.0.1) you have provided on Github. (I am new to Tally & Tally Developer.). 
Now I have few questions and i want to know:
1> Are these all the tables in Tally ? if there are more tables, from where can i get all the table related information to update the existing "database-structure.sql" to add more tables to it? 
2> from where can i get "tally-export-config.yaml" file updated ?
As per your previous comment, I have searched for "field names of Tally in Tally Developers" but it is opening up so many references and not sure which one to look at. 

![image](https://user-images.githubusercontent.com/97693235/149392947-9c778e3f-360d-460e-bac7-b9444b83e3f2.png)

**Comment by dhananjay1405** [comment]
@rvaishnow Tally has tree structure database. I have flattened it, into multiple tables (especially for transaction / voucher). Tally structure you will find in Schema tab of your Tally Developer. If you open that Schema tab of Tally Developer & tally-export-config.yaml & database-structure.sql, and start comparing it, you will notice the whole game. You will have to spend some time in studying it, but once you understand logic, you can literally expand your database with new fields of Tally. I have specifically kept that route open for expanding database as per client requirement.

I have deliberately not documented it fully, as I have seen people attempting to try things without even proper understanding of how RDBMS works, or how SQL Query are written.

**Comment by dhananjay1405** [comment]
@worldfellow @bharatadnani @adarshmadrecha 
I have applied fix. Now utility works perfectly even in Tally Prime 2.0.1
So, closing this thread since issue is resolved now
